
import java.util.LinkedList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author malig
 */
public class KayitEkrani extends javax.swing.JFrame {

    DefaultTableModel model;
    
    KayitIslemleri islemler = new KayitIslemleri();
    
    
    
    /**
     * Creates new form KayitEkrani
     */
    public KayitEkrani() {
        initComponents();
        
        model = (DefaultTableModel)kayit_tablosu.getModel();
        
        kayitlariGoruntule();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kayit_tablosu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kitapAdi_alani = new javax.swing.JTextField();
        kitapYazari_alani = new javax.swing.JTextField();
        kisiAdSoyad_alani = new javax.swing.JTextField();
        kisiTelNo_alani = new javax.swing.JTextField();
        dinamikAra_alani = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ekle_butonu = new javax.swing.JButton();
        mesajYazisi_alani = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        guncelle_butonu = new javax.swing.JButton();
        date = new javax.swing.JTextField();
        sil_butonu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kütüphane Kayıt Sistemi");
        setBounds(new java.awt.Rectangle(400, 300, 0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        kayit_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Kitap Adı", "Kitabın Yazarı", "Teslim Alanın Adı ve Soyadı", "Teslim Alanın Telefon Numarası", "Tarih"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        kayit_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kayit_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(kayit_tablosu);
        if (kayit_tablosu.getColumnModel().getColumnCount() > 0) {
            kayit_tablosu.getColumnModel().getColumn(0).setMinWidth(30);
            kayit_tablosu.getColumnModel().getColumn(0).setMaxWidth(30);
            kayit_tablosu.getColumnModel().getColumn(1).setResizable(false);
            kayit_tablosu.getColumnModel().getColumn(2).setResizable(false);
            kayit_tablosu.getColumnModel().getColumn(3).setResizable(false);
            kayit_tablosu.getColumnModel().getColumn(4).setResizable(false);
            kayit_tablosu.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel1.setText("Kitap Adı : ");

        jLabel2.setText("Kitabın Yazarı : ");

        jLabel3.setText("Teslim Alanın Adı Soyadı  : ");

        jLabel4.setText("Teslim Alanın Tel No  : ");

        dinamikAra_alani.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dinamikAra_alaniKeyReleased(evt);
            }
        });

        jLabel5.setText("Aramak İstediğiniz Kelimeyi Giriniz ");

        ekle_butonu.setBackground(new java.awt.Color(153, 255, 153));
        ekle_butonu.setText("Ekle");
        ekle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle_butonuActionPerformed(evt);
            }
        });

        mesajYazisi_alani.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mesajYazisi_alani.setForeground(new java.awt.Color(51, 51, 255));

        jLabel6.setText("Teslim Aldığı Tarih :");

        guncelle_butonu.setBackground(new java.awt.Color(255, 255, 153));
        guncelle_butonu.setText("Güncelle");
        guncelle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle_butonuActionPerformed(evt);
            }
        });

        sil_butonu.setBackground(new java.awt.Color(255, 51, 51));
        sil_butonu.setText("Sil");
        sil_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_butonuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kitapAdi_alani)
                            .addComponent(kitapYazari_alani)
                            .addComponent(kisiAdSoyad_alani)
                            .addComponent(kisiTelNo_alani)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sil_butonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guncelle_butonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ekle_butonu, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(251, 251, 251)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(dinamikAra_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesajYazisi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dinamikAra_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kitapAdi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(kitapYazari_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(kisiAdSoyad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(kisiTelNo_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(ekle_butonu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(mesajYazisi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guncelle_butonu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sil_butonu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public void kayitlariGoruntule(){
        
        model.setRowCount(0);
        
        LinkedList<Kayit> kayitlar = new LinkedList<Kayit>();
        
        kayitlar = islemler.kayitlariGetir();
        
        if(kayitlar != null){
            
            for(Kayit kayit : kayitlar){
                
                Object[] eklenecek = {kayit.getId(),kayit.getKitapAd(),kayit.getKitapYazar(),kayit.getKisiAdSoyad(),kayit.getTelNo(),kayit.getTarih()};
                
                model.addRow(eklenecek);
                
                
                
            }
            
        }
        
    }
    
    
    public void dinamikAra(String ara){
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        
        kayit_tablosu.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
        
        
        
    }
    
    
    
    
    private void dinamikAra_alaniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dinamikAra_alaniKeyReleased
        
        
        
        String ara = dinamikAra_alani.getText();
        
        dinamikAra(ara);
        
    }//GEN-LAST:event_dinamikAra_alaniKeyReleased

    private void kayit_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayit_tablosuMouseClicked
        
        
        int seciliRow = kayit_tablosu.getSelectedRow();
        
        kitapAdi_alani.setText(model.getValueAt(seciliRow, 1).toString());
        kitapYazari_alani.setText(model.getValueAt(seciliRow, 2).toString());
        kisiAdSoyad_alani.setText(model.getValueAt(seciliRow, 3).toString());
        kisiTelNo_alani.setText(model.getValueAt(seciliRow, 4).toString());
        date.setText(model.getValueAt(seciliRow, 5).toString());
        
    }//GEN-LAST:event_kayit_tablosuMouseClicked

    private void ekle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle_butonuActionPerformed
        
        mesajYazisi_alani.setText("");
        
        String kitapAd = kitapAdi_alani.getText();
        String kitapYazar = kitapYazari_alani.getText();
        String kisiAdSoyad = kisiAdSoyad_alani.getText();
        String kisiTelNo = kisiTelNo_alani.getText();
        String tarih = date.getText();
        
        if(kitapAd.equals("") || kitapYazar.equals("") || kisiAdSoyad.equals("") || kisiTelNo.equals("") || tarih.equals("")){
            
            mesajYazisi_alani.setText("Lütfen kayıt bilgilerini eksiksiz giriniz...");
            return;
            
            
        }
        
        islemler.kayitEkle(kitapAd,kitapYazar,kisiAdSoyad,kisiTelNo,tarih);
        
        
        mesajYazisi_alani.setText("Kitap kaydınız başarıyla oluşturuldu!");
        
        kayitlariGoruntule();
        
        
        
    }//GEN-LAST:event_ekle_butonuActionPerformed

    private void guncelle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle_butonuActionPerformed
        
        mesajYazisi_alani.setText("");
        
        
        String kitapAd = kitapAdi_alani.getText();
        String kitapYazar = kitapYazari_alani.getText();
        String kisiAdSoyad = kisiAdSoyad_alani.getText();
        String kisiTelNo = kisiTelNo_alani.getText();
        String tarih = date.getText();
        
        int seciliRow = kayit_tablosu.getSelectedRow();
        
        
        if(seciliRow == -1){// seçili satır sayısı veya hiç kayıt yok
            
            if(kayit_tablosu.getRowCount() == 0){// tablo boş
                
                mesajYazisi_alani.setText("Lütfen önce kitap kaydı oluşturunuz...");
                
                
            }
            else{// tabloda kayıt var ama biz seçmedik
                mesajYazisi_alani.setText("Lütfen güncellenecek bir kitap kaydı seçiniz...");
            }
            
        }
        else{
            
            int id = (int) kayit_tablosu.getValueAt(seciliRow, 0);
            islemler.kayitGuncelle(id,kitapAd,kitapYazar,kisiAdSoyad,kisiTelNo,tarih);
            
            mesajYazisi_alani.setText("Kitap kaydı başarıyla güncellendi!");
        
            kayitlariGoruntule();
            
        }
        
    }//GEN-LAST:event_guncelle_butonuActionPerformed

    private void sil_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_butonuActionPerformed
        
        mesajYazisi_alani.setText("");
        
        
        int seciliRow = kayit_tablosu.getSelectedRow();
        
        
        if(seciliRow == -1){// seçili satır sayısı veya hiç kayıt yok
            
            if(kayit_tablosu.getRowCount() == 0){// tablo boş
                
                mesajYazisi_alani.setText("Lütfen önce kitap kaydı oluşturunuz...");
                
                
            }
            else{// tabloda kayıt var ama biz seçmedik
                mesajYazisi_alani.setText("Lütfen silinecek bir kitap kaydı seçiniz...");
            }
            
        }
        else{
            
            int id = (int) kayit_tablosu.getValueAt(seciliRow, 0);
            islemler.kayitSil(id);
            
            mesajYazisi_alani.setText("Kitap kaydı başarıyla silindi!");
        
            kayitlariGoruntule();
            
        }
        
        
        
    }//GEN-LAST:event_sil_butonuActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KayitEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KayitEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date;
    private javax.swing.JTextField dinamikAra_alani;
    private javax.swing.JButton ekle_butonu;
    private javax.swing.JButton guncelle_butonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable kayit_tablosu;
    private javax.swing.JTextField kisiAdSoyad_alani;
    private javax.swing.JTextField kisiTelNo_alani;
    private javax.swing.JTextField kitapAdi_alani;
    private javax.swing.JTextField kitapYazari_alani;
    private javax.swing.JLabel mesajYazisi_alani;
    private javax.swing.JButton sil_butonu;
    // End of variables declaration//GEN-END:variables
}
